version: '3.6'
services:
  legba:
    image: evilsocket/legba:latest
    # make sure that the endpoints visible on the host network
    # are visible from the container as well
    network_mode: host
    # used to persist data
    volumes:
      # maps the current working directory to /data
      - .:/data

    deploy:
      resources:
        limits:
          # makes sure that all cpu are used
          cpus: '0.000'
